name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: 1

jobs:
  next-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-toolchain: 1.95.0
          cache: false

      - uses: swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest@0.9.90

      - run: cargo nextest run --all --all-targets --no-fail-fast --locked
